# Uncomment this line to define a global platform for your project
 platform :ios, '8.3'

target 'OneDriveSDK' do
    pod 'ADAL', :git => 'https://github.com/AzureAD/azure-activedirectory-library-for-objc.git', :branch => '1.2.x'
    pod 'Base32', '~> 1.1'
end

target 'OneDriveSDKTests' do
    pod 'OCMock'
end

